---
- hosts: all
  name: update packages
  gather_facts: no
  tasks:
  - name: Update required packages
    ansible.builtin.dnf:
      name: "{{ package_name }}"
      state: latest
      update_only: yes
      update_cache: yes
  - ansible.builtin.debug:
      msg: "On {{ inventory_hostname }} machine, following packages have been installed/updated {{ package_name }}"

