---
- name: Play to Create AWS VPC
  hosts: localhost
  connection: local
  tasks:
    # VPC or Virtual Private Cloud.  The instance will be tied to a subnet that belongs to this particular VPC
    - name: Create AWS VPC aws-demo1-vpc
      amazon.aws.ec2_vpc_net:
        name: "aws-demo1-vpc"
        cidr_block: "192.168.0.0/24"
        region: "{{ ec2_region }}"
        tags:
          Demo: "AWS demo1"
      register: create_vpc
#
    - name: save the create_vpc variable for following job templates
      ansible.builtin.set_stats:
        data:
          vpcid: "{{ create_vpc.vpc.id }}"
        per_host: false
#
    - name: print vpcid
      ansible.builtin.debug:
        msg: "The Demo1 VPC ID is: '{{ create_vpc.vpc.id }}'"
