---
- name: rollback
  hosts: all
  tasks:
    - name: uninstall apache and php
      ansible.builtin.dnf:
        name: httpd,php
        state: absent
    - name: remove index.php file
      ansible.builtin.file:
        path: files/index.php
        state: absent
