---
- name: install web server packages
  hosts: all
  tasks:
  - name: update packages
    ansible.builtin.dnf:
      name: "{{ package_name }}"
      state: latest
      update_cache: yes
      update_only: yes
  - debug:
      msg: "On {{ inventory_hostname }} machine, following packages have been installed/updated {{ package_name }}"
